"""
METRA – Reports Library Router
Standalone router for user's report history, metadata, and tracked downloads.

GET  /api/v1/reports                  → list all reports for current user
GET  /api/v1/reports/{report_id}      → single report detail + summary
GET  /api/v1/reports/{report_id}/download → fresh signed URL + log download event
"""
import logging
from datetime import datetime, timezone
from fastapi import APIRouter, Depends, HTTPException, Request
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func, update

from app.core.database import get_db
from app.core.models import Report, ReportDownload, RoleName, User
from app.core.config import settings
from app.auth.dependencies import get_current_user
from app.audit.logger import audit

logger = logging.getLogger(__name__)
router = APIRouter()

import secrets
from pydantic import BaseModel, Field

def _format_report(r: Report) -> dict:
    """Serialize a Report ORM object to a clean API response dict."""
    now = datetime.now(timezone.utc)
    if r.created_at:
        created_at = r.created_at if r.created_at.tzinfo else r.created_at.replace(tzinfo=timezone.utc)
        days_since = (now - created_at).days
    else:
        days_since = 0
    show_cause_days_remaining = max(0, 15 - days_since)
    is_show_cause_expired = bool(days_since > 15 and (not r.compounding_status or r.compounding_status == "SHOW_CAUSE_AWAITED"))


    return {
        "id":                   r.id,
        "inspection_id":        r.inspection_id,
        "notice_ref":           r.notice_ref,
        "product_name":         r.product_name,
        "category_name":        r.category_name,
        "final_status":         r.final_status,
        "violation_count":      r.violation_count,
        "warning_count":        r.warning_count,
        "extracted_field_count": r.extracted_field_count,
        "download_count":       r.download_count,
        "file_size_bytes":      r.file_size_bytes,
        "created_at":           r.created_at.isoformat() if r.created_at else None,
        "generated_by_name":    r.generator.full_name if r.generator else None,
        "generated_by_email":   r.generator.email if r.generator else None,
        # Section 48 Compounding & CJM Prosecution
        "compounding_status":   r.compounding_status or "SHOW_CAUSE_AWAITED",
        "treasury_challan_no":  r.treasury_challan_no,
        "compounded_amount":    r.compounded_amount,
        "compounded_at":        r.compounded_at.isoformat() if r.compounded_at else None,
        "compounding_cert_ref": r.compounding_cert_ref,
        "days_since_notice":    days_since,
        "show_cause_days_remaining": show_cause_days_remaining,
        "is_show_cause_expired": is_show_cause_expired,
    }


# ── GET /api/v1/reports ───────────────────────────────────────
@router.get("")
async def list_reports(
    limit: int = 50,
    offset: int = 0,
    final_status: str | None = None,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    List all reports generated by the current user, newest first.
    Admins and Supervisors see all reports across all users.
    """
    from sqlalchemy.orm import selectinload

    user_roles = {ur.role.name.value for ur in current_user.user_roles}
    is_privileged = bool(user_roles & {"ADMIN", "SUPERVISOR", "INSPECTOR"})

    query = (
        select(Report)
        .options(selectinload(Report.generator))
        .order_by(Report.created_at.desc())
        .limit(limit)
        .offset(offset)
    )

    # Regular inspectors / manufacturers only see their own reports
    if not is_privileged:
        query = query.where(Report.generated_by == current_user.id)

    if final_status:
        query = query.where(Report.final_status == final_status.upper())

    result = await db.execute(query)
    reports = result.scalars().all()

    # Total count for pagination
    count_query = select(func.count(Report.id))
    if not is_privileged:
        count_query = count_query.where(Report.generated_by == current_user.id)
    if final_status:
        count_query = count_query.where(Report.final_status == final_status.upper())
    total_result = await db.execute(count_query)
    total = total_result.scalar_one()

    return {
        "total": total,
        "limit": limit,
        "offset": offset,
        "reports": [_format_report(r) for r in reports],
    }


# ── GET /api/v1/reports/{report_id} ──────────────────────────
@router.get("/{report_id}")
async def get_report_detail(
    report_id: str,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Full report detail including report_summary JSON and download history."""
    from sqlalchemy.orm import selectinload

    result = await db.execute(
        select(Report)
        .options(
            selectinload(Report.generator),
            selectinload(Report.downloads),
        )
        .where(Report.id == report_id)
    )
    report = result.scalar_one_or_none()
    if not report:
        raise HTTPException(404, {"code": "NOT_FOUND", "message": "Report not found."})

    # Access control: own report or admin/supervisor
    user_roles = {ur.role.name.value for ur in current_user.user_roles}
    is_privileged = bool(user_roles & {"ADMIN", "SUPERVISOR", "INSPECTOR"})
    if not is_privileged and report.generated_by != current_user.id:
        raise HTTPException(403, {"code": "FORBIDDEN", "message": "Access denied."})

    # Recent download events (last 20)
    recent_downloads = sorted(report.downloads, key=lambda d: d.downloaded_at, reverse=True)[:20]

    return {
        **_format_report(report),
        "report_summary": report.report_summary,
        "recent_downloads": [
            {
                "user_id":       d.user_id,
                "ip_address":    d.ip_address,
                "downloaded_at": d.downloaded_at.isoformat(),
            }
            for d in recent_downloads
        ],
    }


# ── GET /api/v1/reports/{report_id}/download ─────────────────
@router.get("/{report_id}/download")
async def download_report(
    report_id: str,
    request: Request,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Returns a fresh 1-hour signed Supabase download URL.
    Logs the download event and increments download_count atomically.
    """
    result = await db.execute(select(Report).where(Report.id == report_id))
    report = result.scalar_one_or_none()
    if not report:
        raise HTTPException(404, {"code": "NOT_FOUND", "message": "Report not found."})

    # Access control
    user_roles = {ur.role.name.value for ur in current_user.user_roles}
    is_privileged = bool(user_roles & {"ADMIN", "SUPERVISOR", "INSPECTOR"})
    if not is_privileged and report.generated_by != current_user.id:
        raise HTTPException(403, {"code": "FORBIDDEN", "message": "Access denied."})

    # Fresh signed URL (1 hour)
    try:
        from supabase import create_client
        supabase = create_client(settings.SUPABASE_URL, settings.SUPABASE_SERVICE_ROLE_KEY)
        signed = supabase.storage.from_(settings.REPORT_BUCKET).create_signed_url(
            report.storage_key, 3600
        )
        download_url = signed.get("signedURL") or signed.get("signedUrl") or ""
    except Exception as e:
        logger.error(f"Failed to generate signed URL for report {report_id}: {e}")
        raise HTTPException(500, {"code": "STORAGE_ERROR", "message": "Could not generate download URL."})

    # ── Log download event ────────────────────────────────────
    client_ip = request.headers.get("x-forwarded-for", request.client.host if request.client else None)
    user_agent = request.headers.get("user-agent", "")[:500]

    dl_event = ReportDownload(
        report_id=report_id,
        user_id=current_user.id,
        ip_address=client_ip,
        user_agent=user_agent,
        downloaded_at=datetime.now(timezone.utc),
    )
    db.add(dl_event)

    # ── Increment download_count atomically ───────────────────
    await db.execute(
        update(Report)
        .where(Report.id == report_id)
        .values(download_count=Report.download_count + 1)
    )
    await db.commit()

    logger.info(f"Report {report_id} downloaded by {current_user.email} "
                f"[ip={client_ip}, total_downloads={report.download_count + 1}]")

    return {
        "report_id":    report_id,
        "download_url": download_url,
        "notice_ref":   report.notice_ref,
        "expires_in":   3600,
    }


# ── POST /api/v1/reports/{report_id}/compound ────────────────
class CompoundingRequest(BaseModel):
    treasury_challan_no: str
    compounded_amount: float = 25000.0
    notes: str | None = None


@router.post("/{report_id}/compound")
async def compound_statutory_notice(
    report_id: str,
    payload: CompoundingRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Section 48 Compounding Settlement Ledger:
    Records Treasury Challan / Bharatkosh payment of compounding fee.
    Discharges notice from criminal prosecution and issues official certificate LMPC/COMP/2026/XXXX.
    """
    user_roles = {ur.role.name.value for ur in current_user.user_roles}
    if not (user_roles & {"ADMIN", "SUPERVISOR", "INSPECTOR"}):
        raise HTTPException(403, "Only enforcement officers may record compounding settlements.")

    report = await db.get(Report, report_id)
    if not report:
        raise HTTPException(404, "Report not found.")

    if report.final_status != "NON_COMPLIANT":
        raise HTTPException(400, "Only non-compliant notices can be compounded.")

    if report.compounding_status == "COMPOUNDED":
        raise HTTPException(409, f"Already compounded under Certificate {report.compounding_cert_ref}.")

    cert_suffix = secrets.token_hex(2).upper() + str(secrets.randbelow(900) + 100)
    now = datetime.now(timezone.utc)
    cert_ref = f"LMPC/COMP/{now.strftime('%Y')}/{cert_suffix}"

    report.compounding_status = "COMPOUNDED"
    report.treasury_challan_no = payload.treasury_challan_no.strip()
    report.compounded_amount = payload.compounded_amount
    report.compounded_at = now
    report.compounding_cert_ref = cert_ref

    await db.commit()
    await db.refresh(report)

    await audit(db, current_user.id, "REPORT_COMPOUNDED", "report", report.id, {
        "notice_ref": report.notice_ref,
        "compounding_cert_ref": cert_ref,
        "treasury_challan_no": payload.treasury_challan_no,
        "compounded_amount": payload.compounded_amount,
    })

    return {
        "success": True,
        "message": f"Offence under notice {report.notice_ref} successfully compounded under Section 48.",
        "compounding_cert_ref": cert_ref,
        "compounding_status": report.compounding_status,
        "treasury_challan_no": report.treasury_challan_no,
        "compounded_amount": report.compounded_amount,
        "compounded_at": report.compounded_at.isoformat(),
        "report": _format_report(report),
    }


# ── POST /api/v1/reports/{report_id}/escalate-cjm ───────────
class CJMEscalationRequest(BaseModel):
    court_name: str | None = "Court of Chief Judicial Magistrate (CJM)"
    notes: str | None = None


@router.post("/{report_id}/escalate-cjm")
async def escalate_to_cjm_court(
    report_id: str,
    payload: CJMEscalationRequest | None = None,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Escalates uncompounded show-cause notices past 15 days to the Court of
    the Chief Judicial Magistrate (CJM) for formal criminal prosecution under Section 36(1).
    """
    user_roles = {ur.role.name.value for ur in current_user.user_roles}
    if not (user_roles & {"ADMIN", "SUPERVISOR", "INSPECTOR"}):
        raise HTTPException(403, "Only enforcement officers may escalate cases for prosecution.")

    report = await db.get(Report, report_id)
    if not report:
        raise HTTPException(404, "Report not found.")

    if report.final_status != "NON_COMPLIANT":
        raise HTTPException(400, "Only non-compliant notices with established violations can be escalated.")

    if report.compounding_status == "COMPOUNDED":
        raise HTTPException(409, "Offence has already been compounded under Section 48; prosecution barred by law.")

    report.compounding_status = "ESCALATED_TO_CJM"
    await db.commit()
    await db.refresh(report)

    await audit(db, current_user.id, "PROSECUTION_ESCALATED_CJM", "report", report.id, {
        "notice_ref": report.notice_ref,
        "court_name": payload.court_name if payload else "Chief Judicial Magistrate",
    })

    return {
        "success": True,
        "message": f"Case {report.notice_ref} escalated for criminal prosecution under Section 36(1) before Chief Judicial Magistrate.",
        "compounding_status": report.compounding_status,
        "report": _format_report(report),
    }

